### ISSUE TITLE
CNF Dataset Generation

### ISSUE THREAD

**Issue by Angelo92Git** [zhaoyu-li/G4SATBench#1]
Hello,

I'm am trying to experiment with the dataset for a course project. When I attempt to generate the k-vercov (Vertex Cover) dataset, I get an error stating that the name "VertexCoverFormulas" cannot be imported from cnfgen. I couldn't find that formula family mentioned in the cnfgen documentation either https://cnfgen.readthedocs.io/en/latest/buildcnf.html

Also, when I try to generate the popularity-similarity (ps) dataset it stalls as it comes close to generating the 800 train instances. (I am using CPU). Why does this behavior occur?

Thank you in advance!

**Comment by zhaoyu-li** [comment]
Hi,

Thanks for your interest. You can use `bash scripts/install.sh` to install the required package (because we have modified the cnfgen package). For PS, we run the generator in parallel for hard instances. The generator for the easy PS dataset should be quite fast.

**Comment by Angelo92Git** [comment]
Thank you very much!
