### ISSUE TITLE
GCN Hyper-parameter tuning

### ISSUE THREAD

**Issue by Angelo92Git** [zhaoyu-li/G4SATBench#3]
Hello, 

I am continuing to work try and experiment with the dataset, and I am looking to replicate the results using GCN on VCG* as a baseline before trying out newer model architectures. If possible do you have any pointers on hyper-parameter selection for GCN? I'm struggling to get an accuracy better than 50%.

I tried generating a simpler dataset (stored in "my_data" in the command below) of random 3-SAT instances all with 17 clauses and 4 variables (close to the critical clause/variable ratio), but it still does not seem to be able to learn to predict satisfiability.

I'd appreciate any advice! Thanks in advance.

```
python train_model.py satisfiability ./my_data/train/ --train_splits sat unsat --valid_dir ./my_data/valid/ --valid_splits sat unsat --label satisfiability --graph vcg --model gcn --n_iterations 6  --lr 1e-04 --weight_decay 1e-08 --scheduler ReduceLROnPlateau --batch_size 128 --seed 123
```

**Comment by zhaoyu-li** [comment]
Hi,

It seems that the primary issue is the limited number of message-passing iterations. In our experiments, we found that setting `n_iterations` to 32 and 64 yielded optimal results. Additionally, the size of the dataset matters. For example, our experiments were conducted with 80k pairs of SAT/UNSAT instances for training, 10k for validation, and 10k for testing.
